export const brazilianStates = [
  { value: 'AC', label: 'Acre', flag: '/images/flags/ac.svg' },
  { value: 'AL', label: 'Alagoas', flag: '/images/flags/al.svg' },
  { value: 'AP', label: 'Amapá', flag: '/images/flags/ap.svg' },
  { value: 'AM', label: 'Amazonas', flag: '/images/flags/am.svg' },
  { value: 'BA', label: 'Bahia', flag: '/images/flags/ba.svg' },
  { value: 'CE', label: 'Ceará', flag: '/images/flags/ce.svg' },
  { value: 'DF', label: 'Distrito Federal', flag: '/images/flags/df.svg' },
  { value: 'ES', label: 'Espírito Santo', flag: '/images/flags/es.svg' },
  { value: 'GO', label: 'Goiás', flag: '/images/flags/go.svg' },
  { value: 'MA', label: 'Maranhão', flag: '/images/flags/ma.svg' },
  { value: 'MT', label: 'Mato Grosso', flag: '/images/flags/mt.svg' },
  { value: 'MS', label: 'Mato Grosso do Sul', flag: '/images/flags/ms.svg' },
  { value: 'MG', label: 'Minas Gerais', flag: '/images/flags/mg.svg' },
  { value: 'PA', label: 'Pará', flag: '/images/flags/pa.svg' },
  { value: 'PB', label: 'Paraíba', flag: '/images/flags/pb.svg' },
  { value: 'PR', label: 'Paraná', flag: '/images/flags/pr.svg' },
  { value: 'PE', label: 'Pernambuco', flag: '/images/flags/pe.svg' },
  { value: 'PI', label: 'Piauí', flag: '/images/flags/pi.svg' },
  { value: 'RJ', label: 'Rio de Janeiro', flag: '/images/flags/rj.svg' },
  { value: 'RN', label: 'Rio Grande do Norte', flag: '/images/flags/rn.svg' },
  { value: 'RS', label: 'Rio Grande do Sul', flag: '/images/flags/rs.svg' },
  { value: 'RO', label: 'Rondônia', flag: '/images/flags/ro.svg' },
  { value: 'RR', label: 'Roraima', flag: '/images/flags/rr.svg' },
  { value: 'SC', label: 'Santa Catarina', flag: '/images/flags/sc.svg' },
  { value: 'SP', label: 'São Paulo', flag: '/images/flags/sp.svg' },
  { value: 'SE', label: 'Sergipe', flag: '/images/flags/se.svg' },
  { value: 'TO', label: 'Tocantins', flag: '/images/flags/to.svg' }
];