export const brazilianStates = [
  { value: 'AC', label: 'Acre', flag: '/images/flags/AC.svg' },
  { value: 'AL', label: 'Alagoas', flag: '/images/flags/AL.svg' },
  { value: 'AP', label: 'Amapá', flag: '/images/flags/AP.svg' },
  { value: 'AM', label: 'Amazonas', flag: '/images/flags/AM.svg' },
  { value: 'BA', label: 'Bahia', flag: '/images/flags/BA.svg' },
  { value: 'CE', label: 'Ceará', flag: '/images/flags/CE.svg' },
  { value: 'DF', label: 'Distrito Federal', flag: '/images/flags/DF.svg' },
  { value: 'ES', label: 'Espírito Santo', flag: '/images/flags/ES.svg' },
  { value: 'GO', label: 'Goiás', flag: '/images/flags/GO.svg' },
  { value: 'MA', label: 'Maranhão', flag: '/images/flags/MA.svg' },
  { value: 'MT', label: 'Mato Grosso', flag: '/images/flags/MT.svg' },
  { value: 'MS', label: 'Mato Grosso do Sul', flag: '/images/flags/MS.svg' },
  { value: 'MG', label: 'Minas Gerais', flag: '/images/flags/MG.svg' },
  { value: 'PA', label: 'Pará', flag: '/images/flags/PA.svg' },
  { value: 'PB', label: 'Paraíba', flag: '/images/flags/PB.svg' },
  { value: 'PR', label: 'Paraná', flag: '/images/flags/PR.svg' },
  { value: 'PE', label: 'Pernambuco', flag: '/images/flags/PE.svg' },
  { value: 'PI', label: 'Piauí', flag: '/images/flags/PI.svg' },
  { value: 'RJ', label: 'Rio de Janeiro', flag: '/images/flags/RJ.svg' },
  { value: 'RN', label: 'Rio Grande do Norte', flag: '/images/flags/RN.svg' },
  { value: 'RS', label: 'Rio Grande do Sul', flag: '/images/flags/RS.svg' },
  { value: 'RO', label: 'Rondônia', flag: '/images/flags/RO.svg' },
  { value: 'RR', label: 'Roraima', flag: '/images/flags/RR.svg' },
  { value: 'SC', label: 'Santa Catarina', flag: '/images/flags/SC.svg' },
  { value: 'SP', label: 'São Paulo', flag: '/images/flags/SP.svg' },
  { value: 'SE', label: 'Sergipe', flag: '/images/flags/SE.svg' },
  { value: 'TO', label: 'Tocantins', flag: '/images/flags/TO.svg' }
];