-- Script SQL para popular a tabela State com os estados brasileiros
INSERT INTO "State" (id, name, flag) VALUES
('AC', 'Acre', '/images/flags/ac.svg'),
('AL', 'Alagoas', '/images/flags/al.svg'),
('AP', 'Amapá', '/images/flags/ap.svg'),
('AM', 'Amazonas', '/images/flags/am.svg'),
('BA', 'Bahia', '/images/flags/ba.svg'),
('CE', 'Ceará', '/images/flags/ce.svg'),
('DF', 'Distrito Federal', '/images/flags/df.svg'),
('ES', 'Espírito Santo', '/images/flags/es.svg'),
('GO', 'Goiás', '/images/flags/go.svg'),
('MA', 'Maranhão', '/images/flags/ma.svg'),
('MT', 'Mato Grosso', '/images/flags/mt.svg'),
('MS', 'Mato Grosso do Sul', '/images/flags/ms.svg'),
('MG', 'Minas Gerais', '/images/flags/mg.svg'),
('PA', 'Pará', '/images/flags/pa.svg'),
('PB', 'Paraíba', '/images/flags/pb.svg'),
('PR', 'Paraná', '/images/flags/pr.svg'),
('PE', 'Pernambuco', '/images/flags/pe.svg'),
('PI', 'Piauí', '/images/flags/pi.svg'),
('RJ', 'Rio de Janeiro', '/images/flags/rj.svg'),
('RN', 'Rio Grande do Norte', '/images/flags/rn.svg'),
('RS', 'Rio Grande do Sul', '/images/flags/rs.svg'),
('RO', 'Rondônia', '/images/flags/ro.svg'),
('RR', 'Roraima', '/images/flags/rr.svg'),
('SC', 'Santa Catarina', '/images/flags/sc.svg'),
('SP', 'São Paulo', '/images/flags/sp.svg'),
('SE', 'Sergipe', '/images/flags/se.svg'),
('TO', 'Tocantins', '/images/flags/to.svg');